secret_list = [
    ['真虚无kid', '这次你真的什么都没抓到.......'],
    ['please give me your eyes', 'PLEASEGIVEMEYOUREYESPLEASEGIVEMEYOUREYESPLEASEGIVEMEYOUREYESPLEASEGIVEMEYOUREYESPLEASEGIVEMEYOUREYESPLEASEGIVEMEYOUREYES']
]